# Сборка технического отчёта (требуется tectonic: brew install tectonic)
.PHONY: pdf clean

pdf:
	tectonic technical_report.tex

clean:
	rm -f technical_report.pdf technical_report.aux technical_report.log technical_report.out technical_report.toc
